"""Transparency label generation.

Maps an attribution result + confidence score to the reader-facing label text
defined in planning.md. The confidence is rendered as a whole-number percent
(0.76 -> "76%").

Three variants, one per attribution result:
    * high_confidence_ai
    * high_confidence_human
    * uncertain
"""

# Verbatim from planning.md's "Transparency Label Design" table. {confidence}
# is filled with a whole-number percentage.
LABEL_TEMPLATES = {
    "high_confidence_ai": (
        "Likely AI-Generated: Our analysis found strong evidence that this "
        "content was generated by AI. Confidence: {confidence}%. This result "
        "is based on automated analysis and may not be perfect. Creators may "
        "appeal this decision."
    ),
    "high_confidence_human": (
        "Likely Human-Written: Our analysis found strong evidence that this "
        "content was written by a person. Confidence: {confidence}%. This "
        "result is based on automated analysis and may not be perfect."
    ),
    "uncertain": (
        "Unable to Determine: Our analysis could not confidently determine "
        "whether this content was written by a person or generated by AI. "
        "Confidence: {confidence}%. No definitive attribution is being made."
    ),
}


def generate_label(result, confidence):
    """Return the transparency label text for an attribution result.

    Args:
        result: One of the keys in ``LABEL_TEMPLATES``.
        confidence: A float in [0, 1]; rendered as a whole-number percent.

    Raises:
        KeyError: If ``result`` is not a recognized attribution result.
    """
    confidence_pct = round(confidence * 100)
    return LABEL_TEMPLATES[result].format(confidence=confidence_pct)