"""Signal 1: LLM-based AI-vs-human classification (Groq-powered).

Asks a Groq model to judge whether submitted text reads as human-written or
AI-generated, looking at tone, flow, organization, and word choice as a whole.

Returns a dict shaped like:

    {
        "signal": "llm",
        "aiScore": 0.82,      # 0.00 = strongly human, 1.00 = strongly AI
        "humanScore": 0.18,   # always 1 - aiScore
        "reason": "..."
    }
"""

import json
import os

from groq import Groq

# A current, generally-available Groq model. Override with GROQ_MODEL if needed.
DEFAULT_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a careful writing-provenance analyst. You judge whether a piece of "
    "text reads as written by a human or generated by an AI language model. "
    "Consider the writing as a whole: tone, flow, organization, word choice, and "
    "whether it feels overly generic, polished, repetitive, or naturally personal.\n\n"
    "Be cautious and honest about uncertainty. Skilled human writing can look "
    "polished, and heavily edited AI writing can look human. When the evidence is "
    "weak (very short text, poetry, non-standard grammar, or an unfamiliar style), "
    "score closer to 0.5 rather than committing to a confident judgment.\n\n"
    "Respond ONLY with a JSON object of this exact shape:\n"
    '{"aiScore": <number 0..1>, "reason": "<one or two sentences>"}\n'
    "Where aiScore is 0.00 for strongly human, 0.50 for unclear, and 1.00 for "
    "strongly AI-generated."
)


def _clamp(value, low=0.0, high=1.0):
    """Clamp a numeric value into the [low, high] range."""
    return max(low, min(high, value))


def analyze_llm_signal(text, client=None):
    """Run the LLM classification signal over ``text``.

    Args:
        text: The submitted writing to analyze.
        client: Optional pre-built ``groq.Groq`` client (useful for testing).
            When omitted, a client is created from the ``GROQ_API_KEY`` env var.

    Returns:
        A signal dict with ``signal``, ``aiScore``, ``humanScore``, and
        ``reason`` keys. On failure it returns a neutral ``aiScore`` of 0.5 so
        the system leans uncertain rather than making a false accusation, plus
        an ``error`` key describing what went wrong.
    """
    if client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            return _error_result("GROQ_API_KEY is not set")
        client = Groq(api_key=api_key)

    model = os.environ.get("GROQ_MODEL", DEFAULT_MODEL)

    try:
        completion = client.chat.completions.create(
            model=model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = completion.choices[0].message.content
        data = json.loads(raw)
    except Exception as exc:  # network, auth, JSON, or schema errors
        return _error_result(f"LLM signal failed: {exc}")

    ai_score = _clamp(float(data.get("aiScore", 0.5)))
    reason = data.get("reason") or "No reason provided by the model."

    return {
        "signal": "llm",
        "aiScore": round(ai_score, 2),
        "humanScore": round(1 - ai_score, 2),
        "reason": reason,
    }


def _error_result(message):
    """Neutral fallback result so failures lean uncertain, not accusatory."""
    return {
        "signal": "llm",
        "aiScore": 0.5,
        "humanScore": 0.5,
        "reason": "Could not complete LLM analysis; defaulting to uncertain.",
        "error": message,
    }